### ISSUE TITLE
RangeError: Invalid time value (at committerDate)

### ISSUE THREAD

**Issue by ElfenB** [conventional-changelog/conventional-changelog#1273]
I get the below error message after upgrading conventional-changelog-conventionalcommits from v7.0.2 to v8.0.0. I think this could be related to PR #1162.

```shell
[7:02:31 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[7:02:31 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (/tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/index.js:80:30)
    at /tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}
RangeError: Invalid time value
    at committerDate (/tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/index.js:80:30)
    at /tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /tmp/workspace/my_project/my_project_repo/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}error Command failed with exit code 1.
```

I ran `git log --pretty=format:'%cd' --date=iso` to see the timestamps of the commit messages which seem fine to me:
```shell
2024-05-16 08:08:55 +0000
2024-05-16 10:07:50 +0200
2024-05-16 10:07:35 +0200
2024-05-16 10:04:11 +0200
2024-05-16 10:03:55 +0200
2024-05-16 09:11:26 +0200
```

Is this an issue on my side or does the timezones support break something here?
Thank you for your support!

**Comment by dangreen** [comment]
Hi

https://github.com/conventional-changelog/conventional-changelog/issues/1267
