### ISSUE TITLE
'RangeError: Invalid time value' in semantic-release/release-notes-generator with conventionalcommits preset after upgrade to 8.0.0

### ISSUE THREAD

**Issue by lwobben** [conventional-changelog/conventional-changelog#1275]
Hi, I'm running the release-notes-generator of semantic release with the conventionalcommits preset in an Azure DevOps pipeline on a Linux agent. Since the conventional-changelog-conventionalcommits update to 8.0.0, a 'RangeError: Invalid time value' is raised. (Downgrading to 7.2.2 solves the problem.)

```
[9:10:50 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:10:50 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:10:50 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (/root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:80:30)
    at /root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}
RangeError: Invalid time value
    at committerDate (/root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:80:30)
    at /root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /root/.nvm/versions/node/v20.12.2/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
} 
```

Used versions:
- node: 20.12.2
- npm: 9.9.3
- semantic-release: 23.0.8
- semantic-release/changelog: 6.0.3
- semantic-release/git: 10.0.1
- semantic-release-ado: 1.4.0

**Comment by dangreen** [comment]
https://github.com/conventional-changelog/conventional-changelog/issues/1267
