### ISSUE TITLE
custom `writerOpts` `transform` no longer able to modify section titles

### ISSUE THREAD

**Issue by Shereef** [conventional-changelog/conventional-changelog#1284]
Hello!
RE: [conventional-changelog-writer](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer)
also reported on https://github.com/semantic-release/release-notes-generator/issues/658

I have https://github.com/Shereef/release-notes-generator-issue repo to show the issue

When we have custom writer opts on [@semantic-release/release-notes-generator@14](https://github.com/semantic-release/release-notes-generator/releases/tag/v14.0.0) it is no longer able to modify the section titles (or anything for that matter)

You can see in the logs [here](https://github.com/Shereef/release-notes-generator-issue/actions/runs/9353866435/job/25745394076#step:5:99):

```
[4:30:18 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot modify immutable object.
    at Object.set (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/commit.js:11:19)
    at transform (/home/runner/work/release-notes-generator-issue/release-notes-generator-issue/.releaserc.writerOpts.js:4:19)
    at transformCommit (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/commit.js:29:23)
    at write (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/writers.js:39:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
Error: Cannot modify immutable object.
    at Object.set (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/commit.js:11:19)
    at transform (/home/runner/work/release-notes-generator-issue/release-notes-generator-issue/.releaserc.writerOpts.js:4:19)
    at transformCommit (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/commit.js:29:23)
    at write (file:///opt/hostedtoolcache/node/20.14.0/x64/lib/node_modules/@semantic-release/release-notes-generator/node_modules/conventional-changelog-writer/dist/writers.js:39:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
```
This happens because in `conventional-changelog-writer/dist/commit.js` it calls the writer opts transform function with `transform(preventModifications(commit), context, options)` so when we try to modify it breaks

What is the new recommended way to do this?

**Comment by dangreen** [comment]
@Shereef Hi. Transform function should return new object (diff, all properties are not required) 

https://github.com/conventional-changelog/conventional-changelog/blob/d3b8aaa16337993bbad4d91db1ffac5a7568756b/packages/conventional-changelog-writer/src/writers.spec.ts#L241-L253

**Comment by Shereef** [comment]
Thank you for the fast response
