### ISSUE TITLE
Parser failing with TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by svsool** [conventional-changelog/conventional-changelog#691]
Parser fails with the following parameters:

```javascript
const { sync } = require("conventional-commits-parser");

console.log(
  sync("Merge pull request #134 from mgmeyers/syntax-decor-flag", {
    mergePattern: "^Merge pull request #(.*) from (.*)$",
    mergeCorrespondence: ["issueId", "source"],
  })
);
```

```
⇣6% ❯ node index.js
.../node_modules/conventional-commits-parser/lib/parser.js:152
    while (!header.trim()) {
                   ^

TypeError: Cannot read property 'trim' of undefined
    at parser (.../node_modules/conventional-commits-parser/lib/parser.js:152:20)
    at sync (.../node_modules/conventional-commits-parser/index.js:97:10)
    at Object.<anonymous> (/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Related problem https://github.com/marvinpinto/actions/issues/20#issuecomment-719964192.

**Comment by Vadorequest** [comment]
PR fix opened at https://github.com/conventional-changelog/conventional-changelog/pull/757

Issue encountered in other repositories:
- https://github.com/marvinpinto/actions/issues/20#issuecomment-719964192
- https://github.com/marvinpinto/actions/issues/65
