### ISSUE TITLE
git-raw-commits breaks release-it: fatal: unrecognized argument: --no-show-signature

### ISSUE THREAD

**Issue by fholzer** [conventional-changelog/conventional-changelog#734]
Recent changes to packages/git-raw-commits/index.js in a0b348c broke release-it for users with old version of git. I didn't check thoroughly, so I might have missed it, but I couldn't find any requirements reg. minimum version of git for use with release-it and related packages.

Here my release-it output:
````
npx release-it --ci --disable-metrics  -VV --npm.skipChecks=true
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD
master
$ git config --get branch.master.remote
origin
$ git remote get-url origin
$ git config --get remote.origin.url
git@REDACTED:REDACTED.git
$ git fetch
$ git describe --tags --abbrev=0
v0.1.0
$ git symbolic-ref HEAD
refs/heads/master
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
origin/master
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote  [cached]
$ git remote get-url origin  [cached]
$ git config --get remote.origin.url  [cached]
$ git fetch  [cached]
$ git describe --tags --abbrev=0  [cached]
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: fatal: unrecognized argument: --no-show-signature
    at Transform._transform (/builds/REDACTED/node_modules/git-raw-commits/index.js:84:30)
    at Transform._read (/builds/REDACTED/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/builds/REDACTED/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/builds/REDACTED/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/builds/REDACTED/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/builds/REDACTED/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:327:22)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:280:11)
Emitted 'error' event on Readable instance at:
    at Transform._transform (/builds/REDACTED/node_modules/git-raw-commits/index.js:84:16)
    at Transform._read (/builds/REDACTED/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:280:11)
````

I'm using git version 1.8.3.1. (Yeah I know it's old)

I couldn't find out which version of git introduced the the `--no-show-signature` switch, but I did find unrelated project which face the same issue. E.g. [here](https://go-review.googlesource.com/c/vgo/+/127956/3/vendor/cmd/go/internal/modfetch/codehost/git.go) the vgo project replaced `--no-show-signature` with `-c log.showsignature=false` which seems to have the same effect.

Would you consider doing the same for this project?

Cheers,
Ferdinand

**Comment by fholzer** [comment]
Just checked, this is actually the most recent available version of git on the most recent CentOS release 🤷‍♂️
````
[root@2dfb1c4798bc test]# cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)
[root@2dfb1c4798bc test]# rpm -q git
git-1.8.3.1-23.el7_8.x86_64
[root@2dfb1c4798bc test]# yum update git
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.easyname.at
 * extras: mirror.easyname.at
 * updates: mirror.easyname.at
No packages marked for update
[root@2dfb1c4798bc test]# git log --no-show-signature
fatal: unrecognized argument: --no-show-signature
[root@2dfb1c4798bc test]#
````

**Comment by fholzer** [comment]
For anyone who finds this, here's my workaround - if you're using yarn:
Add below snippet to your `package.json`, then run `yarn`
````
  "resolutions": {
    "git-raw-commits": "2.0.8"
  }
````

**Comment by fholzer** [comment]
Seems like `--no-show-signature` was introduced with https://github.com/git/git/commit/aa3799996c310da756c7845950def4f6d51cccf3 in git v2.10

**Comment by fholzer** [comment]
@thesmiley1 @bcoe

**Comment by bcoe** [comment]
The change that broke things has been rolled back in https://www.npmjs.com/package/git-raw-commits/v/2.0.10

I think we could address the issue by not setting the option for git unless the user has explicitly set the flag.
