### ISSUE TITLE
bug(conventional-recommended-bump, regex): 'TypeError: val.trim is not a function'

### ISSUE THREAD

**Issue by BinToss** [conventional-changelog/conventional-changelog#849]
`$ conventional-recommended-bump -t v -conventionalcommits`
```
$home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\lib\regex.js:8
      return val.trim()
                 ^

TypeError: val.trim is not a function
    at $home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\lib\regex.js:8:18
    at Array.map (<anonymous>)
    at join ($home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\lib\regex.js:7:6)
    at getNotesRegex ($home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\lib\regex.js:21:33)
    at module.exports ($home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\lib\regex.js:51:19)
    at conventionalCommitsParser ($home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\conventional-commits-parser\index.js:74:15)
    at $home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\index.js:78:15
    at $home\AppData\Roaming\npm\node_modules\conventional-recommended-bump\node_modules\git-semver-tags\index.js:66:5
    at ChildProcess.exithandler (node:child_process:388:7)
    at ChildProcess.emit (node:events:394:28)
```

**Comment by BinToss** [comment]
Agh. I only now noticed a typo in the command. `-conventionalcommits` should be `conventionalcommits`
